### ISSUE TITLE
throw "heap corruption detected" exception  on debug mode 

### ISSUE THREAD

**Issue by denytrans** [snakefoot/cgridlistctrlex#31]
I used virtual mode to edit cell,  it threw "heap corruption detected" exception on debug mode.
I used ms vc2015.
what‘s happening?

	if (m_ComboList.GetSize()>0)
	{
		// Add Fixed Items to ComboBox
		LoadList(m_ComboList, -1);

		// Guess the currently selected item in the list
		CString item = owner.GetItemText(nRow, nCol);
		int nCurSel = m_pComboBox->FindString(-1, item);
		if (nCurSel!=-1)
			m_pComboBox->SetCurSel(nCurSel);
		else
			m_pComboBox->SetWindowText(item);
	}  **//stoped here, it seems that "m_pComboBox" is null
	else
	{
		// Items are going to be added dynamically
		CString item = owner.GetItemText(nRow, nCol);
		m_pComboBox->SetWindowText(item);
	}

**Comment by snakefoot** [comment]
Heap corruption detected is usually means that during the release of memory, then it sees that the guard-area around the memory has been overwritten by some "random" previous operation.

If the m_pComboBox is NULL, then it would give a normal access violation.

I would probably try and use Microsoft Application Verifier, and enable basic-checks for your application. After activating the checks, then just run your application with the debugger attached, and it should break when the "random" operation trashes memory. (Remember to remove your application from Application Verifier as the extra checks really hurts performance)

**Comment by denytrans** [comment]
Thanks regard, I encapsulated CGridListCtrlEx in a "MFC Extended dll", Problem has occurred with this way!

**Comment by snakefoot** [comment]
Don't have much experience with "MFC Extended DLL". Please tell if you find some improvements to the code, so it becomes easier to embed CGridListCtrlEx inside a "MFC Extended DLL".

**Comment by denytrans** [comment]
https://github.com/Widgetsoft/MIS:
You can use this URL to download the complate consumer project dedicated for cgridlistctrlex  that embed it inside a "MFC Extended DLL".The name of the ZIP file is YYGMIS.zip.

**Comment by snakefoot** [comment]
[YYGMIS_ver2.zip](https://github.com/snakefoot/cgridlistctrlex/files/241475/YYGMIS_ver2.zip)

I have updated the DataGridView-project in your solution (See attached file). Please check if the updated version fixes the heap corruption.

P.S. Notice the #define CGRIDLISTCTRLEX_AFX_EXT in the stdafx.h for the YYGMIS-project (And the DataGridView-project)

**Comment by denytrans** [comment]
Thanks in advance for your time and effort, Your help is appreciated.
