### ISSUE TITLE
Redraw list font exception

### ISSUE THREAD

**Issue by phibao37** [snakefoot/cgridlistctrlex#32]
I am subclassing CGridListCtrlEx to show a list of task as follow:
![capture](https://cloud.githubusercontent.com/assets/7576703/16616416/5e540f3e-43a7-11e6-9308-07de66f31a49.PNG)
I need to change font on a row that the asscociated task has "Done" status, so I implement `OnDisplayRowFont` like this:
```
bool TODOGridCtrl::OnDisplayRowFont(int nRow, LOGFONT & font)
{
	//If this is Done task, set italic font
	if (GetItemText(nRow, Task::STATUS) == "Done") {
		
		font.lfItalic = TRUE;
		font.lfStrikeOut = TRUE;
		return true;
	}
	return false;
}
```

But the problem is that when I clear all item (by `DeleteAllItems()`) and re-add data to the list view, sometime it give me an error like this:
![capture2](https://cloud.githubusercontent.com/assets/7576703/16616497/d669241e-43a7-11e6-8319-d4e9a99b1425.PNG)

So, did my `OnDisplayRowFont` implement correct or I must do something else?
And why set font italic make a text bigger than non-italic font, how to reduce the font size?

**Comment by snakefoot** [comment]
If you look at the code, then you will see that you get a blank LOGFONT-struct as input to OnDisplayRowFont(). You will have to fill it out properly, or else the font will be weird.

Like this:

```
bool TODOGridCtrl::OnDisplayRowFont(int nRow, LOGFONT & font)
{
    //If this is Done task, set italic font
    if (GetItemText(nRow, Task::STATUS) == "Done")
    {
        VERIFY(GetCellFont()->GetLogFont(&font) != 0);
        font.lfItalic = TRUE;
        font.lfStrikeOut = TRUE;
        return true;
    }
    return false;
}
```

Are you using multiple threads, and calling DeleteAllItems() from a different thread than the GUI-thread? If not, then you probably have to insert some logging to figure out what happens.

The idea is that before painting the row (CDDS_ITEMPREPAINT) then it can create a font, and after painting a row (CDDS_ITEMPOSTPAINT) then it releases the font again if necessary (m_FontAllocated). Maybe something has broken that protocol for you.

**Comment by phibao37** [comment]
Thank for your help
I inserted `VERIFY(GetCellFont()->GetLogFont(&font) != 0);` and the font display correcly!

**Comment by phibao37** [comment]
I use `OnDisplayCellFont(int nRow, int nCol, LOGFONT& font)` instead and no error occur :+1:
