### ISSUE TITLE
Is there a way to get nItemData from the selected value of CGridColumnTraitCombo?

### ISSUE THREAD

**Issue by sinall** [snakefoot/cgridlistctrlex#38]
There is:
`void CGridColumnTraitCombo::AddItem (DWORD_PTR nItemData, const CString &strItemText)`

But, after nItemData is added, I don't know if there is a way to get it back by passing the corresponding text or get it from cell directly.

**Comment by snakefoot** [comment]
You can read the guide here:

https://www.codeproject.com/Articles/29064/CGridListCtrlEx-Grid-Control-Based-on-CListCtrl

And look at the section about using the ComboBox:

https://www.codeproject.com/Articles/29064/CGridListCtrlEx-Grid-Control-Based-on-CListCtrl

`If wanting to get the itemdata of the CComboBox-item selected, then one can override CGridListCtrlEx::OnEditComplete() and check the parameter value pLVDI->item.lParam. One is required to save the itemdata elsewhere, as it cannot be stored inside the local datamodel of CListCtrl.`
