### ISSUE TITLE
More consistent row to clipboard copy

### ISSUE THREAD

**Issue by bgrahambo** [snakefoot/cgridlistctrlex#40]
When copying to clipboard, the built in functions add a leading tab, and skips cells that don't have any data.  This makes for inconsistent results when trying to copy + paste into spread sheets and wanting to keep columns lined up.  I've made an edit to improve this behavior; use as needed.  (github messes up formatting?  :(  )

bool CRunListCtrlEx::OnDisplayToClipboard(int nRow, CString& strResult) 
{
	const int nColCount = GetColumnCount();

	CString strCellText;
	bool leadingTab = false;
	for (int i = 0; i < nColCount; ++i)
	{
		int nCol = GetHeaderCtrl()->OrderToIndex(i);
		if (!IsColumnVisible(nCol))
			continue;

#if _MFC_VER >= 0x0710
		strCellText.ReleaseBufferSetLength(0);	// Clear without freeing buffer
#else
		strCellText = _T("");
#endif

		if (!CGridListCtrlEx::OnDisplayToClipboard(nRow, nCol, strCellText))
			continue;
		if (leadingTab)
			strResult += _T("\t");
		else
			leadingTab = true;
		strResult += strCellText;
	}
	return true;
}

**Comment by snakefoot** [comment]
@bgrahambo Thank you for the code-improvement. I have committed the changes into the master-branch.
