### ISSUE TITLE
How to get check box click event?

### ISSUE THREAD

**Issue by sevstels** [snakefoot/cgridlistctrlex#44]
Help please  understand how to add a callback for a checkbox click event? Or how to implement a mechanism to track checkbox switching in the application? Thank.

**Comment by snakefoot** [comment]
From the article [CodeProject.com - CGridListCtrlEx](https://www.codeproject.com/Articles/29064/CGridListCtrlEx-Grid-Control-Based-on-CListCtrl)  there is the chapter **Checkbox Support**:

> CGridColumnTraitImage uses the cell image to draw the checkbox, so it is not possible to have both cell image and checkbox in the same column. To get and set the checked / unchecked state, one can use GetCellImage() / SetCellImage().

Not that much experience with LVS_OWNERDATA and LVS_EX_CHECKBOXES

Maybe you have to make this call to make the LVN_ITEMCHANGED notification work:
```
ListCtrl.SetCallbackMask(LVIS_STATEIMAGEMASK);
```

**Comment by sevstels** [comment]
I tried this. The method does not work correctly.  GetCellImage() is called regardless of the user's actions.  I would like to be able to determine in the user program if the checkbox was clicked or not. Where in the library should I insert the callback function when the state of the checkbox changes? Thank you.

**Comment by snakefoot** [comment]
You can override `CGridListCtrlEx::OnEditComplete` and do what you want.

**Comment by sevstels** [comment]
Yes, thank. That helped.

**Comment by snakefoot** [comment]
Closing as answered
